# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: extra182
email: nardienaalthafia@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a website for my Operating Systems extra assignment. Here you can find
  my daily logs with which I take you through my journey of learning how to use
  GitHub + Jekyll. Hope you find my site interesting! (But if you don't, feel free
  to click the exit button :])
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nardienapratama.github.io/extra182" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nardienapratama
github_username:  nardienapratama

# Build settings
author: Nardiéna Althafia Pratama
markdown: kramdown
theme: jekyll-theme-architect
repository: nardienapratama/extra182
plugins:
  - jekyll-feed


# github: [metadata]
encoding: UTF-8
timezone: Asia/Jakarta
show_downloads: true
share: true
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Google Analytics
google_analytics: UA-89852122-1

# plugins:
#   - jekyll-gist
#   - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
